### ISSUE TITLE
Meta: Project Roadmap and Ideas

### ISSUE THREAD

**Issue by federicobond** [intellij-solidity/intellij-solidity#1]
There are many useful things we could start with here:
http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html

In no particular order:
 * [ ] Implement Formatter (code auto-formatting)
 * [ ] Implement Annotators (see [here](https://github.com/duaraghav8/Solium/issues/44) for ideas)
 * [ ] Implement Line Marker providers for usage and definitions of methods and variables.
 * [ ] Implement missing Completion Contributors (may need better static analysis for struct fields)
 * [ ] Implement Reference Contributors
 * [ ] Implement Find Usages Provider
 * [ ] Implement Folding Builder
 * [ ] Implement Go to Symbol Contributor
 * [ ] Implement Structure View Factory
 * [ ] Implement Commenter
 * [ ] Implement Quick Fixes (many annotations could have easy quick fixes)

**Comment by SerCeMan** [comment]
Closing as obsolete
